language: csharp
mono: none
dist: xenial 
sudo: required
os:
  - linux
branches:
  only:
    - master
    - /^release\/.*$/
    - /^feature\/.*$/
    - develop
install: 
  - chmod +x ./dotnet-install.sh
  - ./dotnet-install.sh
script:
  - dotnet build
