language: csharp
mono: none
dist: xenial 
sudo: required
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
os:
  - linux
branches:
  only:
    - master
    - /^release\/.*$/
    - /^feature\/.*$/
    - develop
install: 
  - chmod +x ./dotnet-install.sh
  - ./dotnet-install.sh -Channel Current -Version 3.0.100-preview5-011568
script:
  - /home/travis/.dotnet/dotnet build
