language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.1.4
os:
  - linux
branches:
  only:
    - master
    - /^release\/.*$/
    - /^feature\/.*$/
    - develop
install:
  - dotnet restore
solution: chatle.sln
