language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
mono:
  - 4.2.2
os:
  - linux
  - osx
osx_image: xcode7.1
branches:
  only:
    - master
    - /^release\/.*$/
    - develop
script:
  - ./build.sh --quiet verify
env:
  - KOREBUILD_TEST_SKIPMONO=1
