language: csharp
sudo: required
dist: trusty
mono:
  - latest
os:
  - linux
osx_image: xcode8.2
branches:
  only:
    - master
    - /^release\/.*$/
    - /^feature\/.*$/
    - develop
solution: chatle.sln
