language: csharp
mono: none
os:
  - linux
branches:
  only:
    - master
    - /^release\/.*$/
    - /^feature\/.*$/
    - develop
script:
  - chmod +x ./dotnet-install.sh 
  - ./dotnet-install.sh -Channel Current -Version 3.0.100-preview4-011223 
  - dotnet build
