version: 1.0.0-{build}
skip_tags: true
branches:
  except:
  - gh-pages
install:
  - choco install gitversion.portable -pre -y
  - ps: Install-Product node 6.9.4
  - set path=%programfiles(x86)%\\Microsoft SDKs\TypeScript\2.2;%path%
  - nuget install JetBrains.dotCover.CommandLineTools -ExcludeVersion
init:
- cmd: git config --global core.autocrlf true
environment:
  ASPNETCORE_ENVIRONMENT: Staging
  decrypt_secret:
    secure: I4cwOQ4JlCkdD23TgTvRdkAKOm8AueV0TwqLWAd9lnY=
  FirebaseOptions:TestDatabaseUrl:
    secure: NgkUvSOeZv8qeLIX5tW1qdVJWOuGa1idsXrexYrHVEO4+PgORX4Qk0wkMJg2I6mp
  FirebaseOptions:SecureKey:
    secure: e5dYA2oWrZi1pzu3ovn3J62gNNfxvKYM/QQORHSFFeg=
  access_token:
    secure: FQHQqH6cYqJP4NJ+2KvrqCykj7h3t8IThRC0LY8/Lrs+FIAfRTi4Jam9tkike5KW
before_build:
  - ps: gitversion /l console /output buildserver
  - ps: $env:BuildNumber=$env:APPVEYOR_BUILD_NUMBER
  - cmd: dotnet restore
build_script:
- cmd: build.cmd
test_script:
- cmd: publish.cmd
artifacts:
- path: artifacts\build\*.nupkg
  name: Release
- path: artifacts\chatle.zip
  name: Website
on_success:
  - del test\ChatLe.Cryptography.Test\UtilityTest.cs.enc
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "aguacongas@gmail.com"
  - git config --global user.name "Aguacongas"
  - git checkout gh-pages
  - IF EXIST reports\latest ( rmdir /S /Q reports\latest )
  - IF NOT EXIST reports ( mkdir reports )
  - move coverage\docs reports\latest
  - git add reports\latest
  - git commit reports\latest -m "Appveyor build succed %APPVEYOR_BUILD_NUMBER%"
  - git push
deploy:
- provider: NuGet
  api_key:
    secure: 23wPDdRicGt2vZuJ8vd9TRBKmqjHkx5WjzZmKvyxd5j0fNPedjUScRTj/rT0ObJa
  on:
    branch: 
        - master
        - /release*/
    
