//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("1.1.0.0")]
[assembly: AssemblyVersion("1.1.0.0")]
[assembly: AssemblyInformationalVersion("1.1.0-unstable.43+Branch.develop.Sha.ba6ea7cbc1f369b93b57b4b728b7ca44db584995")]